### ISSUE TITLE
Download link is not working

### ISSUE THREAD

**Issue by rizarae-p** [desai-nisarg/OpenApePose#3]
Thank you for your valuable work!
It seems the download link is not working as it keeps redirecting me to my Trash folder on Google Drive whenever I click on it.
May I ask if you can fix the link? 

Thank you very much!

**Comment by desai-nisarg** [comment]
Apologies. We have been having issues with Google Drive. I have updated the Drive link and have also added a dryad link. Please try again and let me know if you run into issues.

**Comment by rizarae-p** [comment]
Thank you so much for your quick response! I am able to download your dataset now. 😄
